### ISSUE TITLE
python3 logging level setting within file is ignored

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/sm_SensingDC#4]
I'm trying to use python's `logging` standard library, as many of our service modules do. 
I [read in the docs](https://docs.python.org/3/howto/logging.html) that the default logging level is `WARNING`, i.e. levels `INFO` and `DEBUG` won't be recorded.

Sometimes, say for debugging, I might want to lower this level. I include `logging.basicConfig(level=logging.DEBUG)` at the start of the file in which I am calling the logging methods. 

This doesn't seem to make a difference. `logger.info()` and `logger.debug()` calls are not recorded. 
If I make a standalone test script (debian or venv) then the logging works as expected. Hence I suspect this is due to dockerising.
Could the level be overwritten by a parent file? By the entrypoint of the docker container? By docker compose itslef?

**Comment by tobyaharris** [comment]
Check out docker-compose.yml / app.yml. Oft there is a log level set there.
The question remains why this would overrule the whole container?

**Comment by tobyaharris** [comment]
Given I hit this on `feature/recipe-lite` which doesn't have an [`app.yml` specifying log level like `main` does](https://github.com/DigitalShoestringSolutions/sm_SensingDC/blob/9cf1f3a899e928f156d4abb1bff525eef8745b36/dc/app.yml#L6), nor does it use toml.

I've put the [entrypoint in Dockerfile](https://github.com/DigitalShoestringSolutions/sm_SensingDC/blob/f80a7b93037924639b23fbadfbb3916b346e150e/Dockerfile#L45) which doesn't specify a log level. I suspect [this line](https://github.com/DigitalShoestringSolutions/sm_SensingDC/blob/f80a7b93037924639b23fbadfbb3916b346e150e/code/utilities/mqtt_out.py#L29) wasn't working when I opened this.

I'll have to try and reproduce this and return with more details.

**Comment by Greg-Hawkridge** [comment]
It's specified in the app.yml as a command line arguement
